language: android
jdk: oraclejdk8
dist: trusty
sudo: false

env:
  global:
    - ANDROID_API_LEVEL=23
    - EMULATOR_API_LEVEL=29
    - ANDROID_BUILD_TOOLS_VERSION=23.0.2
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis
    - ADB_INSTALL_TIMEOUT=20

android:
  components:
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android-$EMULATOR_API_LEVEL
    - android-24
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script:
  - "./run.sh"
  - ./gradlew clean installDebug
  - ./gradlew check
  - ./gradlew testDebugUnitTest
  - ./gradlew connectedDebugAndroidTest

deploy:
  - provider: releases
    api-key: "$GITHUB_TOKEN"
    file: "$TRAVIS_BUILD_DIR/app/build/outputs/apk/debug/takeme.apk"
    skip_cleanup: true
    name: dev-build-$TRAVIS_TAG
    body: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date
      +'%F %T %Z').
    prerelease: true
    overwrite: true
    target_commitish: "$TRAVIS_COMMIT"
    on:
      tags: true
      branch: develop


after_deploy:
- rm -rf $TRAVIS_BUILD_DIR/app/build/outputs
-
before_install:
  - openssl aes-256-cbc -K $encrypted_5d0773461879_key -iv $encrypted_5d0773461879_iv
    -in keystore.jks.enc -out keystore.jks -d
  - echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
