language: android
jdk: oraclejdk8
dist: trusty
sudo: false
env:
  global:
  - ANDROID_API_LEVEL=23
  - EMULATOR_API_LEVEL=21
  - ANDROID_BUILD_TOOLS_VERSION=29.0.0
  - ANDROID_ABI=armeabi-v7a
  - ANDROID_TAG=google_apis
  - ADB_INSTALL_TIMEOUT=20
android:
  components:
  - platform-tools
  - tools
  - build-tools-$ANDROID_BUILD_TOOLS_VERSION
  - android-$EMULATOR_API_LEVEL
  - android-29
  - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
  - extra-android-m2repository
  licenses:
  - android-sdk-license-.+
  - ".+"

script:
- "./run.sh"
- "./gradlew clean installDebug"
- "./gradlew check"
- "./gradlew build assembleDebug"
- Galaxy S10 SM-G973F, API Level 28
- gcloud firebase test android run --app $TRAVIS_BUILD_DIR/app/build/outputs/apk/debug/app-debug.apk --type=robo --device model=Nexus4,version=19

deploy:
- provider: releases
  api-key: "$GITHUB_TOKEN"
  file: "$TRAVIS_BUILD_DIR/app/build/outputs/apk/debug/takeme.apk"
  skip_cleanup: true
  name: dev-build-$TRAVIS_TAG
  body: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date
    +'%F %T %Z').
  prerelease: true
  overwrite: true
  target_commitish: "$TRAVIS_COMMIT"
  on:
    tags: true
    branch: develop
after_deploy:
- rm -rf $TRAVIS_BUILD_DIR/app/build/outputs

before_install:
- openssl aes-256-cbc -K $encrypted_5d0773461879_key -iv $encrypted_5d0773461879_iv
  -in key.json.enc -out key.json -d
- echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi
  $ANDROID_ABI
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 &
- gcloud version || true
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export $CLOUDSDK_CORE_DISABLE_PROMPTS; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- gcloud version
- openssl aes-256-cbc -K $encrypted_5d0773461879_key -iv $encrypted_5d0773461879_iv
  -in keystore.jks.enc -out keystore.jks -d
