language: android
jdk: oraclejdk8
dist: trusty

android:
  components:
    - platform-tools
    - tools

    - build-tools-29.0.0

    - android-29

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19

script:
  - ./run.sh

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file: $TRAVIS_BUILD_DIR/app/build/outputs/apk/debug/app-debug.apk
  skip_cleanup: true
  name: dev-build-$TRAVIS_TAG
  body: Automatic build of $TRAVIS_BRANCH ($TRAVIS_COMMIT) built by Travis CI on $(date +'%F %T %Z').
  prerelease: true
  overwrite: true
  target_commitish: $TRAVIS_COMMIT
  on:
    tags: true
    branch: develop

after_deploy:
  - rm -rf $TRAVIS_BUILD_DIR/app/build/outputs