language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools

    - build-tools-29.0.0

    - android-29

    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-19


before_install:
  - yes | $HOME/android-sdk/tools/bin/sdkmanager "platforms;android-29"

script:
  - ./run.sh